name: CI
on:
  push:
    branches: [master]
defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build ngcore
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - build: x86_64-linux
          os: ubuntu-latest
        - build: x86_64-macos
          os: macos-latest
        - build: x86_64-windows
          os: windows-latest
          target: x86_64-pc-windows-gnu
        - build: aarch64-linux
          os: ubuntu-latest
          target: aarch64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18'

      - name: Analysis wasman
        run: go vet -v ./...

      - name: Test wasman
        run: go test -v ./...

      - name: Test wasman with race
        run: go test -race -v ./...

      - name: Download external files
        run: go generate ./examples

      - name: Test log example
        run: go run ./examples/log

      - name: Test hoststring example
        run: go run ./examples/hoststring

      - name: Test hostbytes example
        run: go run ./examples/hostbytes
